### ISSUE TITLE
review_pr()'s _normalize_review_action crashes on a non-string action field from the LLM

### ISSUE THREAD

**Issue by philluiz2323** [openvang/vanguarstew#317]
## What happened?

`_normalize_review_action` in `agent/review.py` assumes any *truthy* `action` value from the
LLM is already a string and calls `.strip()` on it directly. When the reviewer LLM returns a
non-string value for `action` (a list, dict, int, or float instead of a string), `review_pr()`
crashes with `AttributeError` instead of falling back to `"comment"` the way every other field
normalizer in the same module already does.

This is the same bug class closed by #294 ("`review_pr()` passes malformed `action`,
`value_label`, and review fields from the LLM"). That fix hardened `_normalize_value_label`
with an explicit `isinstance(label, str)` guard, but `_normalize_review_action` only guards
against *falsy* values (`action or ""`), not against non-string *truthy* values — so the fix
was incomplete for the `action` field itself, and the crash it was supposed to eliminate is
still reachable.

## Steps to reproduce

```python
from agent.review import _normalize_review_action, review_pr

_normalize_review_action(["merge"])
# AttributeError: 'list' object has no attribute 'strip'

_normalize_review_action({"value": "merge"})
# AttributeError: 'dict' object has no attribute 'strip'

# and through the public entrypoint, with a stand-in LLM returning a non-string action:
class LLM:
    def chat_json(self, *a, **k):
        return {"action": ["merge", "reject"], "value_label": "mult:maintenance",
                "scope_ok": True, "tests_present": False, "summary": "s",
                "concerns": [], "recommendation": "r"}

review_pr({"number": 1, "title": "t", "files": []}, None, LLM())
# AttributeError: 'list' object has no attribute 'strip'
```

This is reachable from `python -m scripts.review_pr --repo <r> --pr <n> ...` (the
maintainer-assist path), which feeds live LLM JSON straight into `review_pr()` — a single
malformed `action` field aborts the whole review instead of degrading to `"comment"`.

## Area

agent (agent/, solve entrypoint)

## Python version

3.11

## Relevant logs or output

```
Traceback (most recent call last):
  File "agent/review.py", line 145, in review_pr
    return _normalize_review(out, stub)
  File "agent/review.py", line 106, in _normalize_review
    "action": _normalize_review_action(out.get("action")),
  File "agent/review.py", line 39, in _normalize_review_action
    key = (action or "").strip().lower()
AttributeError: 'list' object has no attribute 'strip'
```

**Comment by vanguarstew** [comment]
This is a clear bug in the agent module, and it's a regression from the incomplete fix in #294. The roadmap prioritizes robustness in the review pipeline, so this fits. The fix is straightforward: add an `isinstance(action, str)` guard in `_normalize_review_action` before calling `.strip()`, falling back to `"comment"` for non-string values. Please open a PR with that change.
