### ISSUE TITLE
objective_score crashes on non-string file path entries in plan or revealed window

### ISSUE THREAD

**Issue by Lang-bt** [openvang/vanguarstew#399]
## Summary

`benchmark/score.py` assumes every entry in a revealed commit's `files` list and a plan item's
`files` list is a string path. `_top_module()` calls `.split("/")` unconditionally, and
`_plan_tokens()` calls `.replace("/", " ")` on each path — so a malformed replay artifact or
LLM-emitted plan with a numeric/list/null `files` entry aborts the whole `objective_score()`
call with `AttributeError`, killing the replay run.

Text fields (`title`, `subject`, `theme`, `kind`) were already hardened in #313; file paths were
missed.

## Impact

Any miner submission or saved revealed window that carries a non-string `files` entry crashes
scoring instead of treating the bad entry as "no path signal", the same fail-soft posture used
elsewhere.

## Repro

```python
from benchmark.score import objective_score, changed_modules, module_recall

changed_modules([{"files": [42, "agent/foo.py"]}])
# AttributeError: 'int' object has no attribute 'split'

module_recall(
    [{"title": "agent work", "files": [None, "agent/plan.py"]}],
    [{"subject": "ship it", "files": ["agent/foo.py"]}],
)
# AttributeError: 'NoneType' object has no attribute 'replace'

objective_score([{"title": "work"}], [{"subject": "x", "files": [42]}])
# same crash
```

## Expected

Skip non-string `files` entries when building module ground truth or plan tokens; well-formed
string paths continue to score normally.

## Where

`benchmark/score.py`: `_top_module`, `_plan_tokens` (and callers `changed_modules`,
`_module_file_counts`, `module_recall`, `objective_score`).

**Comment by vanguarstew** [comment]
This is a clear bug in the scoring pipeline that breaks replay runs on malformed inputs. The fix aligns with the existing fail-soft pattern used for text fields in #313. Please add a guard in `_top_module` and `_plan_tokens` to skip non-string entries; a PR with a test for each crash case would be ideal.

**Comment by matedev01** [comment]
Implemented by #401 and merged into the test branch. Closing as completed.
